# Cleaning

In [147]:
#Import Librarys 

import pandas as pd

In [169]:
ghg_emissions = pd.read_excel('/Users/Shiva/Downloads/caitcountryghgemissions-alldata.xlsx', header=[0,1] , sheet_name='GHG Emissions')

In [170]:
### Chossing countries to study the GHG emission

ghg_emissions[('Unnamed: 0_level_0','Country')].unique()

array(['Afghanistan', 'Albania', 'Algeria', 'Angola', 'Antigua & Barbuda',
       'Argentina', 'Armenia', 'Australia', 'Austria', 'Azerbaijan',
       'Bahamas, The', 'Bahrain', 'Bangladesh', 'Barbados', 'Belarus',
       'Belgium', 'Belize', 'Benin', 'Bhutan', 'Bolivia',
       'Bosnia & Herzegovina', 'Botswana', 'Brazil', 'Brunei', 'Bulgaria',
       'Burkina Faso', 'Burundi', 'Cambodia', 'Cameroon', 'Canada',
       'Cape Verde', 'Central African Republic', 'Chad', 'Chile', 'China',
       'Colombia', 'Comoros', 'Congo, Dem. Rep.', 'Congo, Rep.',
       'Cook Islands', 'Costa Rica', "Cote d'Ivoire", 'Croatia', 'Cuba',
       'Cyprus', 'Czech Republic', 'Denmark', 'Djibouti', 'Dominica',
       'Dominican Republic', 'Ecuador', 'Egypt', 'El Salvador',
       'Equatorial Guinea', 'Eritrea', 'Estonia', 'Ethiopia',
       'European Union (15)', 'European Union (28)', 'Fiji', 'Finland',
       'France', 'Gabon', 'Gambia, The', 'Georgia', 'Germany', 'Ghana',
       'Greece', 'Grenada', 'Guatemala', 'Guinea', 'Guinea-Bissau',
       'Guyana', 'Haiti', 'Honduras', 'Hungary', 'Iceland', 'India',
       'Indonesia', 'Iran', 'Iraq', 'Ireland', 'Israel', 'Italy',
       'Jamaica', 'Japan', 'Jordan', 'Kazakhstan', 'Kenya', 'Kiribati',
       'Korea, Dem. Rep. (North)', 'Korea, Rep. (South)', 'Kuwait',
       'Kyrgyzstan', 'Laos', 'Latvia', 'Lebanon', 'Lesotho', 'Liberia',
       'Libya', 'Lithuania', 'Luxembourg', 'Macedonia, FYR', 'Madagascar',
       'Malawi', 'Malaysia', 'Maldives', 'Mali', 'Malta', 'Mauritania',
       'Mauritius', 'Mexico', 'Moldova', 'Mongolia', 'Montenegro',
       'Morocco', 'Mozambique', 'Myanmar', 'Namibia', 'Nauru', 'Nepal',
       'Netherlands', 'New Zealand', 'Nicaragua', 'Niger', 'Nigeria',
       'Niue', 'Norway', 'Oman', 'Pakistan', 'Palau', 'Panama',
       'Papua New Guinea', 'Paraguay', 'Peru', 'Philippines', 'Poland',
       'Portugal', 'Qatar', 'Romania', 'Russian Federation', 'Rwanda',
       'Saint Kitts & Nevis', 'Saint Lucia', 'Saint Vincent & Grenadines',
       'Samoa', 'Sao Tome & Principe', 'Saudi Arabia', 'Senegal',
       'Serbia', 'Seychelles', 'Sierra Leone', 'Singapore', 'Slovakia',
       'Slovenia', 'Solomon Islands', 'South Africa', 'Spain',
       'Sri Lanka', 'Sudan', 'Suriname', 'Swaziland', 'Sweden',
       'Switzerland', 'Syria', 'Tajikistan', 'Tanzania', 'Thailand',
       'Togo', 'Tonga', 'Trinidad & Tobago', 'Tunisia', 'Turkey',
       'Turkmenistan', 'Uganda', 'Ukraine', 'United Arab Emirates',
       'United Kingdom', 'United States', 'Uruguay', 'Uzbekistan',
       'Vanuatu', 'Venezuela', 'Vietnam', 'World', 'Yemen', 'Zambia',
       'Zimbabwe'], dtype=object)

In [171]:
ghg_emissions.head()

  Unnamed: 0_level_0 Unnamed: 1_level_0  \
             Country               Year
0        Afghanistan               1990
1        Afghanistan               1991
2        Afghanistan               1992
3        Afghanistan               1993
4        Afghanistan               1994

                                                     Emissions Totals  \
  Total GHG Emissions Excluding Land-Use Change and Forestry (MtCO2e)
0                                            15.2969
1                                            15.3514
2                                            14.0513
3                                            14.0649
4                                            14.0222

                                                                        \
  Total GHG Emissions Including Land-Use Change and Forestry (MtCO₂e‍)
0                                            15.9612
1                                            15.3516
2                                            14.0515
3                                            14.0650
4                                            14.0224

                             Emissions by Gas Excluding LUCF  \
  Total CO2 (excluding Land-Use Change and Forestry) (MtCO2)
0                                             2.9907
1                                             2.7412
2                                             1.4252
3                                             1.3520
4                                             1.2971

                                                              \
  Total CH4 (MtCO2e) Total N2O (MtCO2e) Total F-Gas (MtCO2e)
0             9.3098             2.9943               0.0022
1             9.5144             3.0922               0.0036
2             9.5697             3.0513               0.0050
3             9.6081             3.0983               0.0065
4             9.7873             2.9300               0.0079

                             Emissions by Gas Including LUCF  \
  Total CO2 (including Land-Use Change and Forestry) (MtCO2)
0                                           3.654722
1                                           2.741202
2                                           1.425242
3                                           1.352016
4                                           1.297056

                                                               ...  \
  Total CH4 (including Land-Use Change and Forestry) (MtCO2e)  ...
0                                           9.309911           ...
1                                           9.514511           ...
2                                           9.569811           ...
3                                           9.608191           ...
4                                           9.787361           ...

            Emissions by Sector                                      \
  Industrial Processes (MtCO2e) Agriculture (MtCO2e) Waste (MtCO2e)
0                        0.0571               7.3512         4.0390
1                        0.0586               7.6393         4.2200
2                        0.0637               7.6392         4.4011
3                        0.0651               7.7102         4.5822
4                        0.0665               7.7066         4.7633

                                                             \
  Land-Use Change and Forestry (MtCO2) Bunker Fuels (MtCO2)
0                               0.6643                  NaN
1                               0.0002                  NaN
2                               0.0002                  NaN
3                               0.0002                  NaN
4                               0.0002                  NaN

  Energy Emissions by Sub-Sector                                     \
        Electricity/Heat (MtCO2) Manufacturing/Construction (MtCO2)
0                            NaN                                NaN
1                            NaN                                NaN
2                            NaN                                NaN
3                            NaN                                NaN
4                            NaN                                NaN

                                                         \
  Transportation (MtCO2) Other Fuel Combustion (MtCO2e)
0                    NaN                            NaN
1                    NaN                            NaN
2                    NaN                            NaN
3                    NaN                            NaN
4                    NaN                            NaN


  Fugitive Emissions (MtCO2e)
0                      1.2556
1                      1.0226
2                      0.6026
3                      0.4140
4                      0.2473

[5 rows x 22 columns]

In [172]:
ghg_emissions.shape

(4324, 22)

In [173]:
ghg_emissions.isna().sum()

Unnamed: 0_level_0               Country                                                                    0
Unnamed: 1_level_0               Year                                                                       0
Emissions Totals                 Total GHG Emissions Excluding Land-Use Change and Forestry (MtCO2e)      106
                                 Total GHG Emissions Including Land-Use Change and Forestry (MtCO₂e‍)     106
Emissions by Gas Excluding LUCF  Total CO2 (excluding Land-Use Change and Forestry) (MtCO2)                20
                                 Total CH4 (MtCO2e)                                                       104
                                 Total N2O (MtCO2e)                                                       103
                                 Total F-Gas (MtCO2e)                                                       0
Emissions by Gas Including LUCF  Total CO2 (including Land-Use Change and Forestry) (MtCO2)               103
                                 Total CH4 (including Land-Use Change and Forestry) (MtCO2e)              241
                                 Total N2O (including Land-Use Change and Forestry) (MtCO2e)              241
Emissions by Sector              Energy (MtCO2e)                                                         1173
                                 Industrial Processes (MtCO2e)                                            164
                                 Agriculture (MtCO2e)                                                     103
                                 Waste (MtCO2e)                                                             0
                                 Land-Use Change and Forestry (MtCO2)                                     103
                                 Bunker Fuels (MtCO2)                                                    1173
Energy Emissions by Sub-Sector   Electricity/Heat (MtCO2)                                                1173
                                 Manufacturing/Construction (MtCO2)                                      1173
                                 Transportation (MtCO2)                                                  1173
                                 Other Fuel Combustion (MtCO2e)                                          1173
                                 Fugitive Emissions (MtCO2e)                                               64
dtype: int64

In [153]:
ghg_emissions.dtypes

Unnamed: 0_level_0               Country                                                                  object
Unnamed: 1_level_0               Year                                                                      int64
Emissions Totals                 Total GHG Emissions Excluding Land-Use Change and Forestry (MtCO2e)     float64
                                 Total GHG Emissions Including Land-Use Change and Forestry (MtCO₂e‍)    float64
Emissions by Gas Excluding LUCF  Total CO2 (excluding Land-Use Change and Forestry) (MtCO2)              float64
                                 Total CH4 (MtCO2e)                                                      float64
                                 Total N2O (MtCO2e)                                                      float64
                                 Total F-Gas (MtCO2e)                                                    float64
Emissions by Gas Including LUCF  Total CO2 (including Land-Use Change and Forestry) (MtCO2)              float64
                                 Total CH4 (including Land-Use Change and Forestry) (MtCO2e)             float64
                                 Total N2O (including Land-Use Change and Forestry) (MtCO2e)             float64
Emissions by Sector              Energy (MtCO2e)                                                         float64
                                 Industrial Processes (MtCO2e)                                           float64
                                 Agriculture (MtCO2e)                                                    float64
                                 Waste (MtCO2e)                                                          float64
                                 Land-Use Change and Forestry (MtCO2)                                    float64
                                 Bunker Fuels (MtCO2)                                                    float64
Energy Emissions by Sub-Sector   Electricity/Heat (MtCO2)                                                float64
                                 Manufacturing/Construction (MtCO2)                                      float64
                                 Transportation (MtCO2)                                                  float64
                                 Other Fuel Combustion (MtCO2e)                                          float64
                                 Fugitive Emissions (MtCO2e)                                             float64
dtype: object

In [154]:
## STRATIFIED SAMPLE: Filtering the countries that I will study: Egypt','Portugal','India','Japan','Italy','Russian Federation','Angola','Brasil','Netherlands','Australia'


ghg_emissions_filt = ghg_emissions.loc[ghg_emissions[('Unnamed: 0_level_0','Country')].isin(['Brasil','Canada','China','South Africa','Ukraine','Ukraine','France','Australia','India','Costa Rica', 'Nigeria', 'Egypt'])].reset_index()

In [155]:
ghg_emissions_filt.isna().sum()

index                                                                                                    0
Unnamed: 0_level_0               Country                                                                 0
Unnamed: 1_level_0               Year                                                                    0
Emissions Totals                 Total GHG Emissions Excluding Land-Use Change and Forestry (MtCO2e)     2
                                 Total GHG Emissions Including Land-Use Change and Forestry (MtCO₂e‍)    2
Emissions by Gas Excluding LUCF  Total CO2 (excluding Land-Use Change and Forestry) (MtCO2)              0
                                 Total CH4 (MtCO2e)                                                      2
                                 Total N2O (MtCO2e)                                                      2
                                 Total F-Gas (MtCO2e)                                                    0
Emissions by Gas Including LUCF  Total CO2 (including Land-Use Change and Forestry) (MtCO2)              2
                                 Total CH4 (including Land-Use Change and Forestry) (MtCO2e)             2
                                 Total N2O (including Land-Use Change and Forestry) (MtCO2e)             2
Emissions by Sector              Energy (MtCO2e)                                                         0
                                 Industrial Processes (MtCO2e)                                           2
                                 Agriculture (MtCO2e)                                                    2
                                 Waste (MtCO2e)                                                          0
                                 Land-Use Change and Forestry (MtCO2)                                    2
                                 Bunker Fuels (MtCO2)                                                    0
Energy Emissions by Sub-Sector   Electricity/Heat (MtCO2)                                                0
                                 Manufacturing/Construction (MtCO2)                                      0
                                 Transportation (MtCO2)                                                  0
                                 Other Fuel Combustion (MtCO2e)                                          0
                                 Fugitive Emissions (MtCO2e)                                             0
dtype: int64

In [156]:
### Null columns 

ghg_emissions_filt[ghg_emissions_filt.isnull().any(axis=1)]

    index Unnamed: 0_level_0 Unnamed: 1_level_0  \
                     Country               Year
91    942         Costa Rica               2012
183  2897            Nigeria               2012
207  4025            Ukraine               1990
208  4026            Ukraine               1991

                                                       Emissions Totals  \
    Total GHG Emissions Excluding Land-Use Change and Forestry (MtCO2e)
91                                             12.5767
183                                           296.6786
207                                                NaN
208                                                NaN

                                                                          \
    Total GHG Emissions Including Land-Use Change and Forestry (MtCO₂e‍)
91                                              4.9727
183                                           474.8562
207                                                NaN
208                                                NaN

                               Emissions by Gas Excluding LUCF  \
    Total CO2 (excluding Land-Use Change and Forestry) (MtCO2)
91                                              6.7500
183                                            94.1782
207                                           699.6879
208                                           663.7345

                                                                \
    Total CH4 (MtCO2e) Total N2O (MtCO2e) Total F-Gas (MtCO2e)
91              3.6186             1.8433               0.3648
183           165.5269            36.6620               0.3115
207                NaN                NaN               1.3229
208                NaN                NaN               1.2024

                               Emissions by Gas Including LUCF  ...  \
    Total CO2 (including Land-Use Change and Forestry) (MtCO2)  ...
91                                            -0.87686          ...
183                                          267.29725          ...
207                                                NaN          ...
208                                                NaN          ...

              Emissions by Sector                                      \
    Industrial Processes (MtCO2e) Agriculture (MtCO2e) Waste (MtCO2e)
91                            NaN               3.4126         1.5010
183                           NaN              59.1662        66.2932
207                       18.8552                  NaN         8.4282
208                       17.2408                  NaN         8.4523

                                                               \
    Land-Use Change and Forestry (MtCO2) Bunker Fuels (MtCO2)
91                               -7.6040                 0.53
183                             178.1776                 1.81
207                                  NaN                 6.11
208                                  NaN                 5.51

    Energy Emissions by Sub-Sector                                     \
          Electricity/Heat (MtCO2) Manufacturing/Construction (MtCO2)
91                            0.58                               1.02
183                          23.55                               7.80
207                         353.63                             199.74
208                         316.36                             202.41

                                                           \
    Transportation (MtCO2) Other Fuel Combustion (MtCO2e)
91                    4.71                         0.8328
183                  25.20                        55.0152
207                  54.30                        87.1549
208                  65.47                        74.7517


    Fugitive Emissions (MtCO2e)
91                       0.0011
183                     59.3516
207                     87.4037
208                     80.7964

[4 rows x 23 columns]

In [157]:
ghg_emissions_filt.dropna(inplace = True)

In [158]:
## Remove first level of table header ## 

ghg_emissions_filt.columns = ghg_emissions_filt.columns.droplevel()

In [159]:
ghg_emissions_filt.drop(columns = '', inplace = True)

In [167]:
ghg_emissions_filt.columns

Index(['Country', 'Year',
       'Total GHG Emissions Excluding Land-Use Change and Forestry (MtCO2e)',
       'Total GHG Emissions Including Land-Use Change and Forestry (MtCO₂e‍)',
       'Total CO2 (excluding Land-Use Change and Forestry) (MtCO2)',
       'Total CH4 (MtCO2e)', 'Total N2O (MtCO2e)', 'Total F-Gas (MtCO2e)',
       'Total CO2 (including Land-Use Change and Forestry) (MtCO2)',
       'Total CH4 (including Land-Use Change and Forestry) (MtCO2e)',
       'Total N2O (including Land-Use Change and Forestry) (MtCO2e)',
       'Energy (MtCO2e)', 'Industrial Processes (MtCO2e)',
       'Agriculture (MtCO2e)', 'Waste (MtCO2e)',
       'Land-Use Change and Forestry (MtCO2)', 'Bunker Fuels (MtCO2)',
       'Electricity/Heat (MtCO2)', 'Manufacturing/Construction (MtCO2)',
       'Transportation (MtCO2)', 'Other Fuel Combustion (MtCO2e)',
       'Fugitive Emissions (MtCO2e)'],
      dtype='object')

In [178]:
## GHG by the years ## 

ghg_year = ghg_emissions_filt[['Country','Year','Total GHG Emissions Including Land-Use Change and Forestry (MtCO₂e‍)']]


ghg_year

,Country,Year,Total GHG Emissions Including Land-Use Change and Forestry (MtCO₂e‍)
0,Australia,1990,503.7846
1,Australia,1991,495.9580
2,Australia,1992,495.6116
3,Australia,1993,497.0890
4,Australia,1994,504.3664
...,...,...,...
225,Ukraine,2008,393.4963
226,Ukraine,2009,336.1029
227,Ukraine,2010,355.3193
228,Ukraine,2011,371.4599
229,Ukraine,2012,366.3097

In [185]:
### save csv 

#ghg_year.to_csv('GHG_by_year.csv')

In [179]:
## pivot table for mean 

ghg_mean = ghg_emissions_filt.pivot_table( values = ghg_emissions_filt.columns , index = 'Country').drop(columns = 'Year')
                               
ghg_mean

,Agriculture (MtCO2e),Bunker Fuels (MtCO2),Electricity/Heat (MtCO2),Energy (MtCO2e),Fugitive Emissions (MtCO2e),Industrial Processes (MtCO2e),Land-Use Change and Forestry (MtCO2),Manufacturing/Construction (MtCO2),Other Fuel Combustion (MtCO2e),Total CH4 (MtCO2e),Total CH4 (including Land-Use Change and Forestry) (MtCO2e),Total CO2 (excluding Land-Use Change and Forestry) (MtCO2),Total CO2 (including Land-Use Change and Forestry) (MtCO2),Total F-Gas (MtCO2e),Total GHG Emissions Excluding Land-Use Change and Forestry (MtCO2e),Total GHG Emissions Including Land-Use Change and Forestry (MtCO₂e‍),Total N2O (MtCO2e),Total N2O (including Land-Use Change and Forestry) (MtCO2e),Transportation (MtCO2),Waste (MtCO2e)
Country,,,,,,,,,,,,,,,,,,,,
Australia,156.027165,9.701739,195.884783,367.307278,27.972217,12.158700,29.778400,48.904348,20.388113,125.992383,128.518977,338.896535,364.570896,6.103335,550.723778,580.502165,79.731517,81.308962,74.157826,15.231513
Canada,54.998757,5.325217,169.894783,570.416478,49.536804,23.091626,119.676243,94.148261,107.875774,92.720739,102.326408,514.519322,620.601232,11.053126,668.701570,788.377822,50.408378,54.397043,148.960870,20.198170
China,659.307587,20.964783,2134.536957,4741.459961,205.117270,535.932965,-312.050552,1511.050435,570.038343,772.615822,773.296258,4864.214609,4551.004822,79.111135,6121.672552,5809.622030,405.730978,406.209804,320.716957,184.973352
Costa Rica,3.501473,0.619545,0.426364,5.172968,0.000505,0.899936,-0.728327,0.831818,0.672932,3.326023,3.337927,5.536291,4.791107,0.127018,10.691795,9.963477,1.702491,1.707427,3.241364,1.118323
Egypt,25.015778,9.004348,48.071304,137.244883,10.459296,16.288870,-0.431252,33.483913,15.741222,38.157026,38.157037,140.886817,140.455559,2.002765,194.580817,194.149570,13.534213,13.534199,29.489130,16.036526
France,74.798613,21.806522,64.416522,378.399091,3.552852,31.727909,-34.872757,76.394348,108.827100,62.674078,62.687920,377.285957,342.392588,9.373717,501.788917,466.916157,52.455170,52.461942,125.208261,16.864178
India,568.647222,9.091304,606.147391,1230.768004,33.619900,87.744096,-95.182009,258.041739,221.129404,539.242413,540.338643,1161.376343,1064.622235,23.412617,1927.540609,1832.358609,203.509257,203.985121,111.829565,40.382604
Nigeria,47.640236,2.203636,13.897273,146.595777,63.298168,1.892900,181.477991,5.262727,42.728523,133.119559,140.501657,85.244586,256.135387,0.100382,248.615759,430.093745,30.151214,33.356319,21.409091,52.487755
South Africa,30.206609,10.733913,192.059565,323.327135,7.983413,12.197465,1.683448,58.007826,26.908961,42.573743,43.310718,314.629404,315.233187,5.103235,383.468983,385.152452,21.162596,21.505311,38.367391,17.737339
Ukraine,41.275848,0.910000,157.363810,390.461929,55.860771,10.252919,-30.299071,92.898571,52.428767,89.436905,89.604036,336.903014,306.396311,0.949038,450.992510,420.693443,23.703548,23.744060,31.910000,9.001829

In [180]:
columns =['Total GHG Emissions Excluding Land-Use Change and Forestry (MtCO2e)',
       'Total GHG Emissions Including Land-Use Change and Forestry (MtCO₂e‍)',
       'Total CO2 (excluding Land-Use Change and Forestry) (MtCO2)',
       'Total CH4 (MtCO2e)', 'Total N2O (MtCO2e)', 'Total F-Gas (MtCO2e)',
       'Total CO2 (including Land-Use Change and Forestry) (MtCO2)',
       'Total CH4 (including Land-Use Change and Forestry) (MtCO2e)',
       'Total N2O (including Land-Use Change and Forestry) (MtCO2e)',
       'Energy (MtCO2e)', 'Industrial Processes (MtCO2e)',
       'Agriculture (MtCO2e)', 'Waste (MtCO2e)',
       'Land-Use Change and Forestry (MtCO2)', 'Bunker Fuels (MtCO2)',
       'Electricity/Heat (MtCO2)', 'Manufacturing/Construction (MtCO2)',
       'Transportation (MtCO2)', 'Other Fuel Combustion (MtCO2e)',
       'Fugitive Emissions (MtCO2e)']

new_order = columns

In [181]:
ghg_mean = ghg_mean.reindex(new_order, axis=1)

In [182]:
ghg_mean

,Total GHG Emissions Excluding Land-Use Change and Forestry (MtCO2e),Total GHG Emissions Including Land-Use Change and Forestry (MtCO₂e‍),Total CO2 (excluding Land-Use Change and Forestry) (MtCO2),Total CH4 (MtCO2e),Total N2O (MtCO2e),Total F-Gas (MtCO2e),Total CO2 (including Land-Use Change and Forestry) (MtCO2),Total CH4 (including Land-Use Change and Forestry) (MtCO2e),Total N2O (including Land-Use Change and Forestry) (MtCO2e),Energy (MtCO2e),Industrial Processes (MtCO2e),Agriculture (MtCO2e),Waste (MtCO2e),Land-Use Change and Forestry (MtCO2),Bunker Fuels (MtCO2),Electricity/Heat (MtCO2),Manufacturing/Construction (MtCO2),Transportation (MtCO2),Other Fuel Combustion (MtCO2e),Fugitive Emissions (MtCO2e)
Country,,,,,,,,,,,,,,,,,,,,
Australia,550.723778,580.502165,338.896535,125.992383,79.731517,6.103335,364.570896,128.518977,81.308962,367.307278,12.158700,156.027165,15.231513,29.778400,9.701739,195.884783,48.904348,74.157826,20.388113,27.972217
Canada,668.701570,788.377822,514.519322,92.720739,50.408378,11.053126,620.601232,102.326408,54.397043,570.416478,23.091626,54.998757,20.198170,119.676243,5.325217,169.894783,94.148261,148.960870,107.875774,49.536804
China,6121.672552,5809.622030,4864.214609,772.615822,405.730978,79.111135,4551.004822,773.296258,406.209804,4741.459961,535.932965,659.307587,184.973352,-312.050552,20.964783,2134.536957,1511.050435,320.716957,570.038343,205.117270
Costa Rica,10.691795,9.963477,5.536291,3.326023,1.702491,0.127018,4.791107,3.337927,1.707427,5.172968,0.899936,3.501473,1.118323,-0.728327,0.619545,0.426364,0.831818,3.241364,0.672932,0.000505
Egypt,194.580817,194.149570,140.886817,38.157026,13.534213,2.002765,140.455559,38.157037,13.534199,137.244883,16.288870,25.015778,16.036526,-0.431252,9.004348,48.071304,33.483913,29.489130,15.741222,10.459296
France,501.788917,466.916157,377.285957,62.674078,52.455170,9.373717,342.392588,62.687920,52.461942,378.399091,31.727909,74.798613,16.864178,-34.872757,21.806522,64.416522,76.394348,125.208261,108.827100,3.552852
India,1927.540609,1832.358609,1161.376343,539.242413,203.509257,23.412617,1064.622235,540.338643,203.985121,1230.768004,87.744096,568.647222,40.382604,-95.182009,9.091304,606.147391,258.041739,111.829565,221.129404,33.619900
Nigeria,248.615759,430.093745,85.244586,133.119559,30.151214,0.100382,256.135387,140.501657,33.356319,146.595777,1.892900,47.640236,52.487755,181.477991,2.203636,13.897273,5.262727,21.409091,42.728523,63.298168
South Africa,383.468983,385.152452,314.629404,42.573743,21.162596,5.103235,315.233187,43.310718,21.505311,323.327135,12.197465,30.206609,17.737339,1.683448,10.733913,192.059565,58.007826,38.367391,26.908961,7.983413
Ukraine,450.992510,420.693443,336.903014,89.436905,23.703548,0.949038,306.396311,89.604036,23.744060,390.461929,10.252919,41.275848,9.001829,-30.299071,0.910000,157.363810,92.898571,31.910000,52.428767,55.860771

In [183]:
ghg_mean.sort_values(by = 'Total GHG Emissions Excluding Land-Use Change and Forestry (MtCO2e)')

,Total GHG Emissions Excluding Land-Use Change and Forestry (MtCO2e),Total GHG Emissions Including Land-Use Change and Forestry (MtCO₂e‍),Total CO2 (excluding Land-Use Change and Forestry) (MtCO2),Total CH4 (MtCO2e),Total N2O (MtCO2e),Total F-Gas (MtCO2e),Total CO2 (including Land-Use Change and Forestry) (MtCO2),Total CH4 (including Land-Use Change and Forestry) (MtCO2e),Total N2O (including Land-Use Change and Forestry) (MtCO2e),Energy (MtCO2e),Industrial Processes (MtCO2e),Agriculture (MtCO2e),Waste (MtCO2e),Land-Use Change and Forestry (MtCO2),Bunker Fuels (MtCO2),Electricity/Heat (MtCO2),Manufacturing/Construction (MtCO2),Transportation (MtCO2),Other Fuel Combustion (MtCO2e),Fugitive Emissions (MtCO2e)
Country,,,,,,,,,,,,,,,,,,,,
Costa Rica,10.691795,9.963477,5.536291,3.326023,1.702491,0.127018,4.791107,3.337927,1.707427,5.172968,0.899936,3.501473,1.118323,-0.728327,0.619545,0.426364,0.831818,3.241364,0.672932,0.000505
Egypt,194.580817,194.149570,140.886817,38.157026,13.534213,2.002765,140.455559,38.157037,13.534199,137.244883,16.288870,25.015778,16.036526,-0.431252,9.004348,48.071304,33.483913,29.489130,15.741222,10.459296
Nigeria,248.615759,430.093745,85.244586,133.119559,30.151214,0.100382,256.135387,140.501657,33.356319,146.595777,1.892900,47.640236,52.487755,181.477991,2.203636,13.897273,5.262727,21.409091,42.728523,63.298168
South Africa,383.468983,385.152452,314.629404,42.573743,21.162596,5.103235,315.233187,43.310718,21.505311,323.327135,12.197465,30.206609,17.737339,1.683448,10.733913,192.059565,58.007826,38.367391,26.908961,7.983413
Ukraine,450.992510,420.693443,336.903014,89.436905,23.703548,0.949038,306.396311,89.604036,23.744060,390.461929,10.252919,41.275848,9.001829,-30.299071,0.910000,157.363810,92.898571,31.910000,52.428767,55.860771
France,501.788917,466.916157,377.285957,62.674078,52.455170,9.373717,342.392588,62.687920,52.461942,378.399091,31.727909,74.798613,16.864178,-34.872757,21.806522,64.416522,76.394348,125.208261,108.827100,3.552852
Australia,550.723778,580.502165,338.896535,125.992383,79.731517,6.103335,364.570896,128.518977,81.308962,367.307278,12.158700,156.027165,15.231513,29.778400,9.701739,195.884783,48.904348,74.157826,20.388113,27.972217
Canada,668.701570,788.377822,514.519322,92.720739,50.408378,11.053126,620.601232,102.326408,54.397043,570.416478,23.091626,54.998757,20.198170,119.676243,5.325217,169.894783,94.148261,148.960870,107.875774,49.536804
India,1927.540609,1832.358609,1161.376343,539.242413,203.509257,23.412617,1064.622235,540.338643,203.985121,1230.768004,87.744096,568.647222,40.382604,-95.182009,9.091304,606.147391,258.041739,111.829565,221.129404,33.619900
China,6121.672552,5809.622030,4864.214609,772.615822,405.730978,79.111135,4551.004822,773.296258,406.209804,4741.459961,535.932965,659.307587,184.973352,-312.050552,20.964783,2134.536957,1511.050435,320.716957,570.038343,205.117270

In [184]:
ghg_mean['Total GHG Emissions Including Land-Use Change and Forestry (MtCO₂e‍)']

Country
Australia        580.502165
Canada           788.377822
China           5809.622030
Costa Rica         9.963477
Egypt            194.149570
France           466.916157
India           1832.358609
Nigeria          430.093745
South Africa     385.152452
Ukraine          420.693443
Name: Total GHG Emissions Including Land-Use Change and Forestry (MtCO₂e‍), dtype: float64

In [99]:
new_header = emissions.iloc[0] #grab the first row for the header
emissions = emissions[1:] #take the data less the header row
emissions.columns = new_header

In [100]:
emissions

,Country,Year,Total GHG Emissions Excluding Land-Use Change and Forestry (MtCO2e),Total GHG Emissions Including Land-Use Change and Forestry (MtCO₂e‍),Total CO2 (excluding Land-Use Change and Forestry) (MtCO2),Total CH4 (MtCO2e),Total N2O (MtCO2e),Total F-Gas (MtCO2e),Total CO2 (including Land-Use Change and Forestry) (MtCO2),Total CH4 (including Land-Use Change and Forestry) (MtCO2e),...,Industrial Processes (MtCO2e),Agriculture (MtCO2e),Waste (MtCO2e),Land-Use Change and Forestry (MtCO2),Bunker Fuels (MtCO2),Electricity/Heat (MtCO2),Manufacturing/Construction (MtCO2),Transportation (MtCO2),Other Fuel Combustion (MtCO2e),Fugitive Emissions (MtCO2e)
1,Afghanistan,1990,15.2969,15.9612,2.9907,9.3098,2.9943,0.0022,3.65472,9.30991,...,0.0571,7.3512,4.039,0.6643,NaN,NaN,NaN,NaN,NaN,1.2556
2,Afghanistan,1991,15.3514,15.3516,2.7412,9.5144,3.0922,0.0036,2.7412,9.51451,...,0.0586,7.6393,4.22,0.0002,NaN,NaN,NaN,NaN,NaN,1.0226
3,Afghanistan,1992,14.0513,14.0515,1.4252,9.5697,3.0513,0.005,1.42524,9.56981,...,0.0637,7.6392,4.4011,0.0002,NaN,NaN,NaN,NaN,NaN,0.6026
4,Afghanistan,1993,14.0649,14.065,1.352,9.6081,3.0983,0.0065,1.35202,9.60819,...,0.0651,7.7102,4.5822,0.0002,NaN,NaN,NaN,NaN,NaN,0.414
5,Afghanistan,1994,14.0222,14.0224,1.2971,9.7873,2.93,0.0079,1.29706,9.78736,...,0.0665,7.7066,4.7633,0.0002,NaN,NaN,NaN,NaN,NaN,0.2473
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4320,Zimbabwe,2008,23.0814,60.8908,7.5479,9.1397,6.0009,0.3928,45.1605,9.27691,...,0.9914,10.852,0.6351,37.8094,0.02,2.59,1.37,1.02,5.3874,0.2155
4321,Zimbabwe,2009,24.0993,61.7536,8.3881,9.1254,6.1585,0.4273,46.0048,9.15163,...,1.1761,10.9921,0.6353,37.6543,0.02,2.71,1.56,1.09,5.717,0.2189
4322,Zimbabwe,2010,24.9543,62.6195,9.1394,9.1346,6.2185,0.4618,46.7601,9.16567,...,1.2618,11.0582,0.6354,37.6652,0.03,2.95,1.7,1.19,5.9265,0.2223
4323,Zimbabwe,2011,25.9958,63.6836,9.987,9.2276,6.2733,0.508,47.6118,9.2715,...,1.3556,11.1518,0.6635,37.6878,0.03,3.23,1.86,1.31,6.2001,0.2248
4324,Zimbabwe,2012,25.2187,62.9284,9.98,8.9094,5.7752,0.5541,47.6088,8.96583,...,NaN,10.2814,0.6916,37.7097,0.03,3.38,1.95,1.36,6.3736,0.2273